### PR TITLE
Add support for elixir heex files

### PR DESCRIPTION
**Pull request by dan-cooke**
#132 #200

### CODE REVIEW

**Comment by PriceHiller** [comment]
Thanks for the PR @dan-cooke!

Did you ever get a chance to test this for elixir heex files?

**Comment by dan-cooke** [comment]
@PriceHiller so I’ve tested briefly , it works for normal HTML tags but anything with dots in them - it does not complete

Eg 

<.button will not work

I am not sure how best to handle this with the plugin, any ideas?

**Comment by PriceHiller** [comment]
Wow, that was a fast response.

So the unfortunate bit is that we register to a keybind in insert mode triggered by tag openers and closers.

See https://github.com/windwp/nvim-ts-autotag/blob/e239a560f338be31337e7abc3ee42515daf23f5e/lua/nvim-ts-autotag/internal.lua#L466

and https://github.com/windwp/nvim-ts-autotag/blob/e239a560f338be31337e7abc3ee42515daf23f5e/lua/nvim-ts-autotag/internal.lua#L478

In effect, that means we'd have to create a keybind that maps to `.` and then looks one character back for a `<` to trigger an autoclose. That may lead to other issues in how we manage the tags, would have to try to know for sure.

I'm not familiar with `heex`, does it not create a tag on a closing `>` or a `/`?

I'm good with merging this if you're happy with the functionality added by the alias.

**Comment by PriceHiller** [comment]
Closed by #223, thanks for the attempt 🙂

**Pull request closed without merging**
