### PR TITLE
Major Fork Merge (including upstream breakages and unmerged PRs)

### PR DESCRIPTION
**Pull request by PriceHiller**
Hello, on the recommendation of @folke (https://github.com/windwp/nvim-ts-autotag/pull/171#issuecomment-2118689969), I've opened a PR to track against my fork.

I'm opening this PR including all of my changes on my fork I've begun maintaining until you (@windwp ) are back.

This should serve as a diff between the two and once you are back you can review and merge.

If this is too large (which it likely is), please ping me and I can see about chunking my fork up and doing smaller PRs to you so its reviewable.

At the time of writing my fork does the following:
- Requires Neovim `0.9.5` or greater 
- Completely removes `nvim-treesitter` as a hard dependency and instead uses `vim.treesitter`
- Overhauls the tests so a simple `make test` downloads all dependencies for the plugin and runs the tests
- Fixed the tests so now they should all pass
- ~CI is using my own self-hosted runner, so CI changes should ***not*** be merged~
- Completely overhauled the `setup`, allowing for per filetype customization and global customization.
  - This also allows end users to extend or override the existing tag configurations for the defined filetypes. This was done in the hopes that if a upstream TS parser breaks, a user isn't screwed until we update `nvim-ts-autotag` to support it
- Deprecates `nvim-treesitter` setup methods, instead opting for `require("nvim-ts-autotag").setup({ ... })`
- Uses `vim.keymap.set` for bindings
- Supporting additional filetypes like `twig` and `blade`
- Fixing close errors as a result of only partially parsed updates in the treesitter tree (https://github.com/PriceHiller/nvim-ts-autotag/commit/a92a4e97ec9b14e61eefd4e81b581474c509f0a0)
- ~Replaced the *Sponsor* section in the README with the *Fork Status* -- this should ***not*** be merged as is~

And undoubtedly more as time goes on.

Thanks for the plugin, and looking forward to eventually having you back 🙂

### CODE REVIEW

**Comment by windwp** [comment]
hi i still use this plugin so i will keep maintain  it.

**Comment by PriceHiller** [comment]
> hi i still use this plugin so i will keep maintain it.

That's great to hear 🙂!

I've made some significant changes on my fork. Would you like to start breaking up my fork into smaller PRs for individual review?

You may want to take a look at my fork and decide what you  definitely *don't* want, like the new setup method.

**Comment by folke** [comment]
@windwp just to be clear, `nvim-ts-autotag` doesn't break right now with the latest Neovim nightly/stable and the latest `nvim-treesitter`.

There is however a big `nvim-treesitter` [rewrite](https://github.com/nvim-treesitter/nvim-treesitter/tree/main) under way and initially that was planned to be released together with Neovim 0.10, but has currently been postponed to Neovim 0.11. (See also @clason)

Either way, it's still a good idea to remove the `nvim-treesitter` dependency, since Neovim has all the required functionality since `0.9.x` and this way `nvim-ts-autotag` wouldn't break once the rewrite gets released.

**Comment by clason** [comment]
Indeed; you can look at nvim-treesitter-context (and nvim-treesitter-textobjects on the `main` branch) to see how you can structure your plugin without relying on (deprecated!) nvim-treesitter-module.

**Comment by folke** [comment]
It seems my [PR](https://github.com/windwp/nvim-ts-autotag/pull/171) got merged, so all good now :)

https://github.com/windwp/nvim-ts-autotag/pull/171

**Comment by windwp** [comment]
hi @PriceHiller 
i just check that PR and it fix  some issue with embed template  on ruby and allow user can customize template . so i will merge it . 
What is the selfhosted CI nix-runner?
Can you keep my test runner and i will merge.
Thank you

**Comment by PriceHiller** [comment]
I changed the CI over to mine because I got frustrated when debugging a CI issue 😅

When I get time later I'll restore the previous CI runner and ping you

**Comment by PriceHiller** [comment]
@windwp this should be ready to go now.

You may want to run the CI for this prior to merging -- tests pass on my fork: https://github.com/PriceHiller/nvim-ts-autotag/actions/runs/9147532305

**Comment by PriceHiller** [comment]
Another thing worth review, is the deprecation notices I've placed at `1.0.0`. I started following Semantic(ish) Versioning on my fork. I intended to fully remove some features when I did the first `1.0.0` release.

I can modify those deprecations messages or do something with 'em if you'd like. Just let me know.

**Comment by PriceHiller** [comment]
REMINDER TO SELF: Once this gets merged/chunked then merged add an additional commit warning new downstream users to come back to the main repo -- staying on my fork shouldn't be necessary once this is merged.

**Comment by windwp** [comment]
i merge it, thank

**Comment by PriceHiller** [comment]
Cool, I'll update my fork to point users to go back over here.

As a note, my fork was intended in good-faith in case that wasn't clear. I figured you were burnt-out, didn't have enough time, or something else -- after all, it's a free project.

I accepted the invite you sent for collaboration, I'm happy to assist with maintenance. It may be a good idea to ping me with what type of stuff you'd be ok with me merging; I don't want to incorporate changes that are undesired as it's your project first and foremost.

Please ping me if there's anything I do that you want rolled back :smile:.

**Pull request merged**
