### PR TITLE
Add rust file supports 

### PR DESCRIPTION
**Pull request by Alt-iOS**
Some frameworks like yew and leptos allow for html inside rust files, just updating implementation of [rayliwell](https://github.com/rayliwell) to add it to the og and keep just one plugin

### CODE REVIEW

**Comment by PriceHiller** [comment]
Thanks for the PR!

Can you do 2 things for me:
1. Run `make format` at the toplevel to reformat the code (you'll need `stylua` installed).
2. Can you supply me with a sample of some rust code with embedded html so I can create tests for it later (just add a comment with it)

If you do those two things, I'll merge this in 🙂

**Comment by Alt-iOS** [comment]
Thanks a lot!! Heres an example of a simple button inside a component in leptos and formatted the lua files.
```rust
#[component]
pub fn App() -> impl IntoView {
	provide_meta_context();
	view! {
		<Stylesheet id="leptos" href="/pkg/{{project-name}}.css"/>
		<button
			class="bg-blue-500 hover:bg-blue-700 text-white font-bold py-2 px-4 rounded"
		>

			"Hello world!"
		</button>
	}
}
```

**Comment by PriceHiller** [comment]
Awesome, thanks again 😄

(Tests failing are not your fault)

**Comment by rayliwell** [comment]
Happy to see this got upstreamed,

I've updated the docs and archived the repo :)

**Pull request merged**
