### PR TITLE
fix: update tag patterns to support new XML TS tags

### LINKED ISSUE #163: Doesn't close tags in XML
Thanks for your work on this plugin! 

I've been trying to get the auto-closing to work for xml files (this is important for Java projects since working with the POM can be a pain otherwise) but it doesn't seem to work. [Here](https://github.com/jonathanmorris180/nvim/blob/main/lua/jonathan/plugins/nvim-treesitter.lua) is my nvim-treesitter config.

Please let me know if more info is needed.

### PR DESCRIPTION
**Pull request by PriceHiller**
It seems the upstream Treesitter tags for `xml` was updated and is no longer 100% identical to the `html` syntax tree.

## XML Tree according to `:InspectTree`
image

## HTML Tree according to `:InspectTree`
image

Notice the tags now differ between the two.

Closes #163

### CODE REVIEW

**Comment by ydalton** [comment]
Yep, applying this patch fixes the issue.

**Comment by PriceHiller** [comment]
Hey @windwp, pinging you to get your thoughts on this PR if you have time. 

It's been working well for me this far. 

Thanks 🙂

**Comment by PriceHiller** [comment]
For anyone subscribed to this PR, please see my comment: https://github.com/windwp/nvim-ts-autotag/issues/163#issuecomment-2107013155

Gist is I'll be maintaining a fork @ https://github.com/PriceHiller/nvim-ts-autotag/ until such a time the author comes back.

**Comment by PriceHiller** [comment]
Closed in favor of #173

**Pull request closed without merging**
