### PR TITLE
feat: allow tag renaming for normal mode operations like x and d motions

### LINKED ISSUE #81: Make automatic renaming work with `x`and `d`
Currently if I have a tag and try to change it with `x` if I made a typo, it does not update the closing tag.

example (cursor: `|`)

```html
<form|r|>
</formr>
```

pressing `x` results in

```html
<form|>|
</formr>
```

However I would expect autotag to fix my typo this way.

Currently it seems to only work in insert mode, so if I pressed `s<ESC>` instead it would update to what I wanted.

### PR DESCRIPTION
**Pull request by ribru17**
Fixes #81

### CODE REVIEW

**Comment by ribru17** [comment]
NOTE: I didn't know how to implement tests for this as it seems they are hard coded to only account for insert mode renaming. To get around this I added an insert operation at the end of each test but this is not ideal obviously. Would appreciate help in that category. Other than that tests mostly showcase what this commit makes possible, as well as the limitations.

**Comment by PriceHiller** [comment]
It appears the primary maintainer is currently preoccupied and hasn't been responding (https://github.com/windwp/nvim-ts-autotag/issues/163#issuecomment-2107013155). Not a dig against them, they've provided a great plugin at no charge.

In the meantime, I'll be maintaing a fork until they're back @ https://github.com/PriceHiller/nvim-ts-autotag/.

@ribru17 with my copypasta now pasted, was there anything *wrong* with this PR that would keep it from being merged? If there wasn't I may be merging this into my fork.

**Comment by ribru17** [comment]
Thanks for doing that! Nothing wrong with this PR except for the fact that the tests aren't really legitimate and don't test anything. I wasn't able to get the autocmd to run in the testing environment sadly, but if one were to check this out and run it on their machine everything would work fine (at least, as of when I committed it). So I think it is good to merge without tests. I can remove them if need be

**Comment by PriceHiller** [comment]
Great to hear that it works, I'd include the tests you added and I can debug later as to why they're non-functional. 

Currently I'm trying to wrangle existing tests into working order, so if you want to PR to me on my fork with your changes I'll definitely take a look and most likely merge.

If you don't have the time, I'll get around to merging this myself after I get the current tests passing whenever that is.

**Pull request closed without merging**
