### PR TITLE
fix: wrap vim.treesitter.get_parser in pcall

### PR DESCRIPTION
**Pull request by cbochs**
Fixes https://github.com/windwp/nvim-ts-autotag/issues/183

Tested manually on a local ruby erb file. Please let me know if you would like other tests added for this.

### CODE REVIEW

**Comment by PriceHiller** [comment]
Thanks for the PR @cbochs, it's much appreciated!

I hate to be a pain, but there's (unfortunately) more than one place where we call `vim.treesitter.get_parser`.

If you could update your commit wrapping those up too, I'll gladly merge this.

If you don't want to do that, no problem -- I can open a separate PR later tonight to do so.

---
*I really need to set aside a bit of time to do some light refactoring and depulication across the `internal.lua` file, kinda scuffed in some spots 😝*

**Comment by cbochs** [comment]
Oh yes, I just noticed this myself. Apologies for the half-baked PR! I will clean it up here

**Comment by PriceHiller** [comment]
> Apologies for the half-baked PR!

Apologies for the kinda scuffed code lol. No problem, just ping me when you're good to go/request a review from me.

Thanks again 🙂

**Comment by cbochs** [comment]
Just fixed the few other calls to `vim.treesitter.get_parser`. There appear to be a few failing tests, but I think they're also failing on the main branch:

<details>
<summary>Failing tests</summary>

```
Fail    ||      [rename tag] test 21 rescript rename open tag
            ./tests/utils/helpers.lua:58:

             text error: 21 rescript rename open tag

            Expected objects to be the same.
            Passed in:
            (string) '<lala> dsadsa </div> '
            Expected:
            (string) '<lala> dsadsa </lala> '

            stack traceback:
                ./tests/utils/helpers.lua:58: in function 'compare_text'
                ./tests/utils/helpers.lua:136: in function <./tests/utils/helpers.lua:78>

Fail    ||      [rename tag] test 22 rescript rename open tag with attr
            ./tests/utils/helpers.lua:58:

             text error: 22 rescript rename open tag with attr

            Expected objects to be the same.
            Passed in:
            (string) '<lala class="lla"> dsadsa </div> '
            Expected:
            (string) '<lala class="lla"> dsadsa </lala> '

            stack traceback:
                ./tests/utils/helpers.lua:58: in function 'compare_text'
                ./tests/utils/helpers.lua:136: in function <./tests/utils/helpers.lua:78>

Fail    ||      [rename tag] test 23 rescript rename close tag with attr
            ./tests/utils/helpers.lua:58:

             text error: 23 rescript rename close tag with attr

            Expected objects to be the same.
            Passed in:
            (string) '<div class="lla"> dsadsa </lala> '
            Expected:
            (string) '<lala class="lla"> dsadsa </lala> '

            stack traceback:
                ./tests/utils/helpers.lua:58: in function 'compare_text'
                ./tests/utils/helpers.lua:136: in function <./tests/utils/helpers.lua:78>
```

</details>

However, I did find the following error - which appeared when running `make test` on the main branch has been fixed with this PR:

<details>
<summary>Error message</summary>

```
< [SETUP] Finished setting up minimal initError detected while processing command line..InsertLeave Autocommands for "<buffer=4>":
< Error executing lua callback: ...arm64/share/nvim/runtime/lua/vim/treesitter/language.lua:107: no parser for 'rescript' language, see :help treesitter-parsers
< stack traceback:
<       [C]: in function 'error'
<       ...arm64/share/nvim/runtime/lua/vim/treesitter/language.lua:107: in function 'add'
<       ...4/share/nvim/runtime/lua/vim/treesitter/languagetree.lua:111: in function 'new'
<       ...im-macos-arm64/share/nvim/runtime/lua/vim/treesitter.lua:41: in function '_create_parser'
<       ...im-macos-arm64/share/nvim/runtime/lua/vim/treesitter.lua:108: in function 'get_parser'
<       ...ersonal/nvim-ts-autotag/lua/nvim-ts-autotag/internal.lua:433: in function <...ersonal/nvim-ts-autotag/lua/nvim-ts-autotag/internal.lua:431>
<       [builtin#36]: at 0x010055a1a4
<       .../tests/.deps/plugins/plenary.nvim/lua/plenary/busted.lua:268: in function 'run'
<       [string ":lua"]:1: in main chunkError executing lua callback: ...arm64/share/nvim/runtime/lua/vim/treesitter/language.lua:107: no parser for 'rescript' language, see :help treesitter-parsers
< stack traceback:
<       [C]: in function 'error'
<       ...arm64/share/nvim/runtime/lua/vim/treesitter/language.lua:107: in function 'add'
<       ...4/share/nvim/runtime/lua/vim/treesitter/languagetree.lua:111: in function 'new'
<       ...im-macos-arm64/share/nvim/runtime/lua/vim/treesitter.lua:41: in function '_create_parser'
<       ...im-macos-arm64/share/nvim/runtime/lua/vim/treesitter.lua:108: in function 'get_parser'
<       ...ersonal/nvim-ts-autotag/lua/nvim-ts-autotag/internal.lua:433: in function <...ersonal/nvim-ts-autotag/lua/nvim-ts-autotag/internal.lua:431>
<       [builtin#36]: at 0x010055a1a4
<       .../tests/.deps/plugins/plenary.nvim/lua/plenary/busted.lua:268: in function 'run'
<       [string ":lua"]:1: in main chunkError executing lua callback: ...arm64/share/nvim/runtime/lua/vim/treesitter/language.lua:107: no parser for 'rescript' language, see :help treesitter-parsers
< stack traceback:
<       [C]: in function 'error'
<       ...arm64/share/nvim/runtime/lua/vim/treesitter/language.lua:107: in function 'add'
<       ...4/share/nvim/runtime/lua/vim/treesitter/languagetree.lua:111: in function 'new'
<       ...im-macos-arm64/share/nvim/runtime/lua/vim/treesitter.lua:41: in function '_create_parser'
<       ...im-macos-arm64/share/nvim/runtime/lua/vim/treesitter.lua:108: in function 'get_parser'
<       ...ersonal/nvim-ts-autotag/lua/nvim-ts-autotag/internal.lua:433: in function <...ersonal/nvim-ts-autotag/lua/nvim-ts-autotag/internal.lua:431>
<       [builtin#36]: at 0x010055a1a4
<       .../tests/.deps/plugins/plenary.nvim/lua/plenary/busted.lua:268: in function 'run'
<       [string ":lua"]:1: in main chunk
```

</details>

**Comment by PriceHiller** [comment]
>  There appear to be a few failing tests, but I think they're also failing on the main branch

You probably don't have the `treesitter-cli` or  `nodejs` installed locally which I think the rescript parser is using to generate some grammars.

Tests pass in CI, so it's probably just fine. 

Looking good, thanks for the PR!

**Pull request merged**
